import { Inter } from "next/font/google";
import "../style/globals.css";

import StyleProvider from "@/components/organism/StyleProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Brand",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyleProvider>
        {children}
        </StyleProvider>
      </body>
    </html>
  );
}
